---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dwdemo
  labels:
    app: dwdemo
    owner: nathan-fisher
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dwdemo
  template:
    metadata:
      labels:
        app: dwdemo
        owner: nathan-fisher
        version: "0.0.1"
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:

          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - dwdemo
              topologyKey: "kubernetes.io/hostname"
            weight: 10
      containers:
      - name: dwdemo
        image: 192.168.253.99:5001/dwdemo:latest
        ports:
        - name: http
          containerPort: 8080
        - name: http-admin
          containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: dwdemo
spec:
  clusterIP: None
  selector:
    app: dwdemo
  ports:
    - name: http
      port: 8080
      targetPort: http
    - name: http-admin
      port: 8081
      targetPort: http-admin
